export const GET_ALL ="GET_ALL"
export const GET_DETAIL="GET_DETAIL"
export const FIND_RECIPE= "FIND_RECIPE"
export const All_DIETS ="All_DIETS"
export const FIND_DIET="FIND_DIET"
export const NEXT ="NEXT"
export const PREV ="PREV"
export const ORDER = "ORDER"
export const ORDER_ALFA = "ORDER_ALFA"
export const ORDER_API = "ORDER_API"

